/**
 * A script to perform the following:
 *   1. Read icons from department-of-veterans-affairs/mobile-assets package 'icons' folder
 *   2. Process the icons into UpperCamelCase and arrange data for writing
 *   3. Output the results as src/components/Icon/iconList.ts file that is pulled into Icon.tsx
 */

// eslint-disable-next-line
const fs = require('fs')

const importLocation = '@department-of-veterans-affairs/mobile-assets/icons'

const iconList = []
const iconImportPathList = {}

/**
 * Function to massage SVG file name to an UpperCamelCase icon name
 * @param name - String of SVG file name
 * @returns UpperCamelCase icon name
 */
function parseName(name) {
  if (name === 'vads') return '' // Remove 'vads' from list; it is a folder, not file
  if (name.startsWith('vads/')) name = name.replace('vads/', '') // Remove 'vads/' folder prefix
  // Convert name to UpperCamelCase
  name =
    name.charAt(0).toUpperCase() +
    name.substring(1).replace(/_./g, (letter) => letter[1].toUpperCase())
  name = name.replace('.svg', '') // Remove file type

  if (name === 'Tty') return 'TTY' // Correction for acronym name

  return name
}

/**
 * Function to build the content of the output file
 */
function formIconListFile() {
  let fileContent = ''

  // Set file header
  fileContent +=
    '/** This file is automatically generated by `yarn buildIcons` */ \n\n'

  // Build named import list
  for (const icon of iconList) {
    fileContent += `import ${icon} from '${iconImportPathList[icon]}'\n`
  }

  // Build IconMap object
  fileContent += '\nexport const IconMap = {\n'
  for (const icon of iconList) {
    fileContent += `  ${icon},\n`
  }
  fileContent += '}\n'

  return fileContent
}

/** Begin script */

// Retrieve icon files from assets package
const files = fs.readdirSync(`../../node_modules/${importLocation}`, {
  recursive: true,
})

// Process icons list into requisite icon data
for (const file of files) {
  const iconName = parseName(file)
  const importPath = `${importLocation}/${file}`

  if (!iconName) continue

  iconList.push(iconName)
  iconImportPathList[iconName] = importPath
}

// Sort icon data
iconList.sort()

// Form file content and create iconList.ts
fs.writeFile(
  './src/components/Icon/iconList.ts',
  formIconListFile(),
  (error) => {
    if (error) return console.log('writeFile error: ', error)
    return console.log('Successfully created iconList.ts!')
  },
)
