/** This file is automatically generated by `yarn buildIcons` */ 

import AccountCircle from '@department-of-veterans-affairs/mobile-assets/icons/AccountCircle.svg'
import Add from '@department-of-veterans-affairs/mobile-assets/icons/Add.svg'
import Building from '@department-of-veterans-affairs/mobile-assets/icons/Building.svg'
import Bullet from '@department-of-veterans-affairs/mobile-assets/icons/Bullet.svg'
import Calendar from '@department-of-veterans-affairs/mobile-assets/icons/Calendar.svg'
import Check from '@department-of-veterans-affairs/mobile-assets/icons/Check.svg'
import CheckBoxEmpty from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxEmpty.svg'
import CheckBoxError from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxError.svg'
import CheckBoxFilled from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxFilled.svg'
import CheckBoxIntermediate from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxIntermediate.svg'
import ChevronDown from '@department-of-veterans-affairs/mobile-assets/icons/ChevronDown.svg'
import ChevronLeft from '@department-of-veterans-affairs/mobile-assets/icons/ChevronLeft.svg'
import ChevronRight from '@department-of-veterans-affairs/mobile-assets/icons/ChevronRight.svg'
import ChevronUp from '@department-of-veterans-affairs/mobile-assets/icons/ChevronUp.svg'
import CircleCheckMark from '@department-of-veterans-affairs/mobile-assets/icons/CircleCheckMark.svg'
import Compose from '@department-of-veterans-affairs/mobile-assets/icons/Compose.svg'
import Description from '@department-of-veterans-affairs/mobile-assets/icons/Description.svg'
import DescriptionOutline from '@department-of-veterans-affairs/mobile-assets/icons/DescriptionOutline.svg'
import Directions from '@department-of-veterans-affairs/mobile-assets/icons/Directions.svg'
import Ellipsis from '@department-of-veterans-affairs/mobile-assets/icons/Ellipsis.svg'
import ExclamationCircle from '@department-of-veterans-affairs/mobile-assets/icons/ExclamationCircle.svg'
import ExclamationTriangle from '@department-of-veterans-affairs/mobile-assets/icons/ExclamationTriangle.svg'
import ExternalLink from '@department-of-veterans-affairs/mobile-assets/icons/ExternalLink.svg'
import FileInvoiceDollar from '@department-of-veterans-affairs/mobile-assets/icons/FileInvoiceDollar.svg'
import FileInvoiceDollarOutline from '@department-of-veterans-affairs/mobile-assets/icons/FileInvoiceDollarOutline.svg'
import Folder from '@department-of-veterans-affairs/mobile-assets/icons/Folder.svg'
import Home from '@department-of-veterans-affairs/mobile-assets/icons/Home.svg'
import HomeOutline from '@department-of-veterans-affairs/mobile-assets/icons/HomeOutline.svg'
import Inbox from '@department-of-veterans-affairs/mobile-assets/icons/Inbox.svg'
import Info from '@department-of-veterans-affairs/mobile-assets/icons/Info.svg'
import Lock from '@department-of-veterans-affairs/mobile-assets/icons/Lock.svg'
import MedicalServices from '@department-of-veterans-affairs/mobile-assets/icons/MedicalServices.svg'
import MedicalServicesOutline from '@department-of-veterans-affairs/mobile-assets/icons/MedicalServicesOutline.svg'
import Minus from '@department-of-veterans-affairs/mobile-assets/icons/Minus.svg'
import PaperClip from '@department-of-veterans-affairs/mobile-assets/icons/PaperClip.svg'
import Phone from '@department-of-veterans-affairs/mobile-assets/icons/Phone.svg'
import QuestionMark from '@department-of-veterans-affairs/mobile-assets/icons/QuestionMark.svg'
import RadioEmpty from '@department-of-veterans-affairs/mobile-assets/icons/RadioEmpty.svg'
import RadioFilled from '@department-of-veterans-affairs/mobile-assets/icons/RadioFilled.svg'
import Redo from '@department-of-veterans-affairs/mobile-assets/icons/Redo.svg'
import Remove from '@department-of-veterans-affairs/mobile-assets/icons/Remove.svg'
import Reply from '@department-of-veterans-affairs/mobile-assets/icons/Reply.svg'
import Sort from '@department-of-veterans-affairs/mobile-assets/icons/Sort.svg'
import TTY from '@department-of-veterans-affairs/mobile-assets/icons/TTY.svg'
import Text from '@department-of-veterans-affairs/mobile-assets/icons/Text.svg'
import Trash from '@department-of-veterans-affairs/mobile-assets/icons/Trash.svg'
import Truck from '@department-of-veterans-affairs/mobile-assets/icons/Truck.svg'
import Unread from '@department-of-veterans-affairs/mobile-assets/icons/Unread.svg'
import VideoCamera from '@department-of-veterans-affairs/mobile-assets/icons/VideoCamera.svg'

export const IconMap = {
  AccountCircle,
  Add,
  Building,
  Bullet,
  Calendar,
  Check,
  CheckBoxEmpty,
  CheckBoxError,
  CheckBoxFilled,
  CheckBoxIntermediate,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheckMark,
  Compose,
  Description,
  DescriptionOutline,
  Directions,
  Ellipsis,
  ExclamationCircle,
  ExclamationTriangle,
  ExternalLink,
  FileInvoiceDollar,
  FileInvoiceDollarOutline,
  Folder,
  Home,
  HomeOutline,
  Inbox,
  Info,
  Lock,
  MedicalServices,
  MedicalServicesOutline,
  Minus,
  PaperClip,
  Phone,
  QuestionMark,
  RadioEmpty,
  RadioFilled,
  Redo,
  Remove,
  Reply,
  Sort,
  TTY,
  Text,
  Trash,
  Truck,
  Unread,
  VideoCamera,
}
