/** This file is automatically generated by `yarn buildIcons` */ 

import AccessibilityNew from '@department-of-veterans-affairs/mobile-assets/icons/vads/accessibility_new.svg'
import AccessibleForward from '@department-of-veterans-affairs/mobile-assets/icons/vads/accessible_forward.svg'
import AccountBalance from '@department-of-veterans-affairs/mobile-assets/icons/vads/account_balance.svg'
import AccountBox from '@department-of-veterans-affairs/mobile-assets/icons/vads/account_box.svg'
// import AccountCircle from '@department-of-veterans-affairs/mobile-assets/icons/AccountCircle.svg'
import AccountCircle from '@department-of-veterans-affairs/mobile-assets/icons/vads/account_circle.svg'
// import Add from '@department-of-veterans-affairs/mobile-assets/icons/Add.svg'
import Add from '@department-of-veterans-affairs/mobile-assets/icons/vads/add.svg'
import AddCircle from '@department-of-veterans-affairs/mobile-assets/icons/vads/add_circle.svg'
import AddCircleOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/add_circle_outline.svg'
import Adjust from '@department-of-veterans-affairs/mobile-assets/icons/vads/adjust.svg'
import Alarm from '@department-of-veterans-affairs/mobile-assets/icons/vads/alarm.svg'
import AlternateEmail from '@department-of-veterans-affairs/mobile-assets/icons/vads/alternate_email.svg'
import Announcement from '@department-of-veterans-affairs/mobile-assets/icons/vads/announcement.svg'
import Api from '@department-of-veterans-affairs/mobile-assets/icons/vads/api.svg'
import AppStore from '@department-of-veterans-affairs/mobile-assets/icons/vads/app_store.svg'
import ArrowBack from '@department-of-veterans-affairs/mobile-assets/icons/vads/arrow_back.svg'
import ArrowDownward from '@department-of-veterans-affairs/mobile-assets/icons/vads/arrow_downward.svg'
import ArrowDropDown from '@department-of-veterans-affairs/mobile-assets/icons/vads/arrow_drop_down.svg'
import ArrowDropUp from '@department-of-veterans-affairs/mobile-assets/icons/vads/arrow_drop_up.svg'
import ArrowForward from '@department-of-veterans-affairs/mobile-assets/icons/vads/arrow_forward.svg'
import ArrowUpward from '@department-of-veterans-affairs/mobile-assets/icons/vads/arrow_upward.svg'
import Assessment from '@department-of-veterans-affairs/mobile-assets/icons/vads/assessment.svg'
import Assignment from '@department-of-veterans-affairs/mobile-assets/icons/vads/assignment.svg'
import AssignmentTurnedIn from '@department-of-veterans-affairs/mobile-assets/icons/vads/assignment_turned_in.svg'
import AttachFile from '@department-of-veterans-affairs/mobile-assets/icons/vads/attach_file.svg'
import AttachMoney from '@department-of-veterans-affairs/mobile-assets/icons/vads/attach_money.svg'
import Autorenew from '@department-of-veterans-affairs/mobile-assets/icons/vads/autorenew.svg'
import Backpack from '@department-of-veterans-affairs/mobile-assets/icons/vads/backpack.svg'
import Bathtub from '@department-of-veterans-affairs/mobile-assets/icons/vads/bathtub.svg'
import Bedding from '@department-of-veterans-affairs/mobile-assets/icons/vads/bedding.svg'
import Bookmark from '@department-of-veterans-affairs/mobile-assets/icons/vads/bookmark.svg'
import BugReport from '@department-of-veterans-affairs/mobile-assets/icons/vads/bug_report.svg'
import Build from '@department-of-veterans-affairs/mobile-assets/icons/vads/build.svg'
import Building from '@department-of-veterans-affairs/mobile-assets/icons/Building.svg'
import Bullet from '@department-of-veterans-affairs/mobile-assets/icons/Bullet.svg'
import Calendar from '@department-of-veterans-affairs/mobile-assets/icons/Calendar.svg'
import CalendarToday from '@department-of-veterans-affairs/mobile-assets/icons/vads/calendar_today.svg'
import Campaign from '@department-of-veterans-affairs/mobile-assets/icons/vads/campaign.svg'
import Camping from '@department-of-veterans-affairs/mobile-assets/icons/vads/camping.svg'
import Cancel from '@department-of-veterans-affairs/mobile-assets/icons/vads/cancel.svg'
import Chat from '@department-of-veterans-affairs/mobile-assets/icons/vads/chat.svg'
// import Check from '@department-of-veterans-affairs/mobile-assets/icons/Check.svg'
import Check from '@department-of-veterans-affairs/mobile-assets/icons/vads/check.svg'
import CheckBox from '@department-of-veterans-affairs/mobile-assets/icons/check_box.svg'
import CheckBoxEmpty from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxEmpty.svg'
// import CheckBoxError from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxError.svg'
import CheckBoxError from '@department-of-veterans-affairs/mobile-assets/icons/check_box_error.svg'
import CheckBoxFilled from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxFilled.svg'
import CheckBoxIntermediate from '@department-of-veterans-affairs/mobile-assets/icons/CheckBoxIntermediate.svg'
// import CheckBoxOutlineBlank from '@department-of-veterans-affairs/mobile-assets/icons/check_box_outline_blank.svg'
import CheckBoxOutlineBlank from '@department-of-veterans-affairs/mobile-assets/icons/vads/check_box_outline_blank.svg'
import CheckCircle from '@department-of-veterans-affairs/mobile-assets/icons/vads/check_circle.svg'
import CheckCircleOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/check_circle_outline.svg'
import Checkroom from '@department-of-veterans-affairs/mobile-assets/icons/vads/checkroom.svg'
import ChevronDown from '@department-of-veterans-affairs/mobile-assets/icons/ChevronDown.svg'
// import ChevronLeft from '@department-of-veterans-affairs/mobile-assets/icons/ChevronLeft.svg'
import ChevronLeft from '@department-of-veterans-affairs/mobile-assets/icons/vads/chevron_left.svg'
// import ChevronRight from '@department-of-veterans-affairs/mobile-assets/icons/ChevronRight.svg'
import ChevronRight from '@department-of-veterans-affairs/mobile-assets/icons/vads/chevron_right.svg'
import ChevronUp from '@department-of-veterans-affairs/mobile-assets/icons/ChevronUp.svg'
import CircleCheckMark from '@department-of-veterans-affairs/mobile-assets/icons/CircleCheckMark.svg'
import CleanHands from '@department-of-veterans-affairs/mobile-assets/icons/vads/clean_hands.svg'
import Close from '@department-of-veterans-affairs/mobile-assets/icons/vads/close.svg'
import ClosedCaption from '@department-of-veterans-affairs/mobile-assets/icons/vads/closed_caption.svg'
import Clothes from '@department-of-veterans-affairs/mobile-assets/icons/vads/clothes.svg'
import Cloud from '@department-of-veterans-affairs/mobile-assets/icons/vads/cloud.svg'
import Code from '@department-of-veterans-affairs/mobile-assets/icons/vads/code.svg'
import Comment from '@department-of-veterans-affairs/mobile-assets/icons/vads/comment.svg'
import Compose from '@department-of-veterans-affairs/mobile-assets/icons/Compose.svg'
import ConnectWithoutContact from '@department-of-veterans-affairs/mobile-assets/icons/vads/connect_without_contact.svg'
import Construction from '@department-of-veterans-affairs/mobile-assets/icons/vads/construction.svg'
import ConstructionWorker from '@department-of-veterans-affairs/mobile-assets/icons/vads/construction_worker.svg'
import ContactPage from '@department-of-veterans-affairs/mobile-assets/icons/vads/contact_page.svg'
import ContentCopy from '@department-of-veterans-affairs/mobile-assets/icons/vads/content_copy.svg'
import Coronavirus from '@department-of-veterans-affairs/mobile-assets/icons/vads/coronavirus.svg'
import CreditCard from '@department-of-veterans-affairs/mobile-assets/icons/vads/credit_card.svg'
import Deck from '@department-of-veterans-affairs/mobile-assets/icons/vads/deck.svg'
import Delete from '@department-of-veterans-affairs/mobile-assets/icons/vads/delete.svg'
// import Description from '@department-of-veterans-affairs/mobile-assets/icons/Description.svg'
import Description from '@department-of-veterans-affairs/mobile-assets/icons/vads/description.svg'
import DescriptionOutline from '@department-of-veterans-affairs/mobile-assets/icons/DescriptionOutline.svg'
import DescriptionOutlined from '@department-of-veterans-affairs/mobile-assets/icons/description_outlined.svg'
import DeviceThermostat from '@department-of-veterans-affairs/mobile-assets/icons/vads/device_thermostat.svg'
// import Directions from '@department-of-veterans-affairs/mobile-assets/icons/Directions.svg'
import Directions from '@department-of-veterans-affairs/mobile-assets/icons/vads/directions.svg'
import DirectionsBike from '@department-of-veterans-affairs/mobile-assets/icons/vads/directions_bike.svg'
import DirectionsBus from '@department-of-veterans-affairs/mobile-assets/icons/vads/directions_bus.svg'
import DirectionsCar from '@department-of-veterans-affairs/mobile-assets/icons/vads/directions_car.svg'
import DirectionsWalk from '@department-of-veterans-affairs/mobile-assets/icons/vads/directions_walk.svg'
import DoNotDisturb from '@department-of-veterans-affairs/mobile-assets/icons/vads/do_not_disturb.svg'
import DoNotTouch from '@department-of-veterans-affairs/mobile-assets/icons/vads/do_not_touch.svg'
import DragHandle from '@department-of-veterans-affairs/mobile-assets/icons/vads/drag_handle.svg'
import Eco from '@department-of-veterans-affairs/mobile-assets/icons/vads/eco.svg'
import Edit from '@department-of-veterans-affairs/mobile-assets/icons/vads/edit.svg'
import ElectricalServices from '@department-of-veterans-affairs/mobile-assets/icons/vads/electrical_services.svg'
import Ellipsis from '@department-of-veterans-affairs/mobile-assets/icons/Ellipsis.svg'
import EmojiEvents from '@department-of-veterans-affairs/mobile-assets/icons/vads/emoji_events.svg'
import Error from '@department-of-veterans-affairs/mobile-assets/icons/vads/error.svg'
import ErrorOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/error_outline.svg'
import Event from '@department-of-veterans-affairs/mobile-assets/icons/vads/event.svg'
import EventAvailable from '@department-of-veterans-affairs/mobile-assets/icons/vads/event_available.svg'
import ExclamationCircle from '@department-of-veterans-affairs/mobile-assets/icons/ExclamationCircle.svg'
import ExclamationTriangle from '@department-of-veterans-affairs/mobile-assets/icons/ExclamationTriangle.svg'
import ExpandLess from '@department-of-veterans-affairs/mobile-assets/icons/vads/expand_less.svg'
import ExpandMore from '@department-of-veterans-affairs/mobile-assets/icons/vads/expand_more.svg'
import ExternalLink from '@department-of-veterans-affairs/mobile-assets/icons/ExternalLink.svg'
import Facebook from '@department-of-veterans-affairs/mobile-assets/icons/vads/facebook.svg'
import FastForward from '@department-of-veterans-affairs/mobile-assets/icons/vads/fast_forward.svg'
import FastRewind from '@department-of-veterans-affairs/mobile-assets/icons/vads/fast_rewind.svg'
import Favorite from '@department-of-veterans-affairs/mobile-assets/icons/vads/favorite.svg'
import FavoriteBorder from '@department-of-veterans-affairs/mobile-assets/icons/vads/favorite_border.svg'
import Fax from '@department-of-veterans-affairs/mobile-assets/icons/vads/fax.svg'
import FileDownload from '@department-of-veterans-affairs/mobile-assets/icons/vads/file_download.svg'
import FileInvoiceDollar from '@department-of-veterans-affairs/mobile-assets/icons/FileInvoiceDollar.svg'
import FileInvoiceDollarOutline from '@department-of-veterans-affairs/mobile-assets/icons/FileInvoiceDollarOutline.svg'
import FilePresent from '@department-of-veterans-affairs/mobile-assets/icons/vads/file_present.svg'
import FileUpload from '@department-of-veterans-affairs/mobile-assets/icons/vads/file_upload.svg'
import FilterAlt from '@department-of-veterans-affairs/mobile-assets/icons/vads/filter_alt.svg'
import FilterList from '@department-of-veterans-affairs/mobile-assets/icons/vads/filter_list.svg'
import Fingerprint from '@department-of-veterans-affairs/mobile-assets/icons/vads/fingerprint.svg'
import FirstPage from '@department-of-veterans-affairs/mobile-assets/icons/vads/first_page.svg'
import Flag from '@department-of-veterans-affairs/mobile-assets/icons/vads/flag.svg'
import Flickr from '@department-of-veterans-affairs/mobile-assets/icons/vads/flickr.svg'
import Flight from '@department-of-veterans-affairs/mobile-assets/icons/vads/flight.svg'
import Flooding from '@department-of-veterans-affairs/mobile-assets/icons/vads/flooding.svg'
// import Folder from '@department-of-veterans-affairs/mobile-assets/icons/Folder.svg'
import Folder from '@department-of-veterans-affairs/mobile-assets/icons/vads/folder.svg'
import FolderOpen from '@department-of-veterans-affairs/mobile-assets/icons/vads/folder_open.svg'
import FormatQuote from '@department-of-veterans-affairs/mobile-assets/icons/vads/format_quote.svg'
import FormatSize from '@department-of-veterans-affairs/mobile-assets/icons/vads/format_size.svg'
import Forum from '@department-of-veterans-affairs/mobile-assets/icons/vads/forum.svg'
import Github from '@department-of-veterans-affairs/mobile-assets/icons/vads/github.svg'
import GooglePlay from '@department-of-veterans-affairs/mobile-assets/icons/vads/google_play.svg'
import GridView from '@department-of-veterans-affairs/mobile-assets/icons/vads/grid_view.svg'
import GroupAdd from '@department-of-veterans-affairs/mobile-assets/icons/vads/group_add.svg'
import Groups from '@department-of-veterans-affairs/mobile-assets/icons/vads/groups.svg'
import Handshake from '@department-of-veterans-affairs/mobile-assets/icons/vads/handshake.svg'
import Hearing from '@department-of-veterans-affairs/mobile-assets/icons/vads/hearing.svg'
import HearingDisabled from '@department-of-veterans-affairs/mobile-assets/icons/vads/hearing_disabled.svg'
import Help from '@department-of-veterans-affairs/mobile-assets/icons/vads/help.svg'
import HelpOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/help_outline.svg'
import HighlightOff from '@department-of-veterans-affairs/mobile-assets/icons/vads/highlight_off.svg'
import History from '@department-of-veterans-affairs/mobile-assets/icons/vads/history.svg'
// import Home from '@department-of-veterans-affairs/mobile-assets/icons/Home.svg'
import Home from '@department-of-veterans-affairs/mobile-assets/icons/vads/home.svg'
import HomeOutline from '@department-of-veterans-affairs/mobile-assets/icons/HomeOutline.svg'
import HomeOutlined from '@department-of-veterans-affairs/mobile-assets/icons/home_outlined.svg'
import Hospital from '@department-of-veterans-affairs/mobile-assets/icons/vads/hospital.svg'
import Hotel from '@department-of-veterans-affairs/mobile-assets/icons/vads/hotel.svg'
import HourglassEmpty from '@department-of-veterans-affairs/mobile-assets/icons/vads/hourglass_empty.svg'
import HowToReg from '@department-of-veterans-affairs/mobile-assets/icons/vads/how_to_reg.svg'
import Hurricane from '@department-of-veterans-affairs/mobile-assets/icons/vads/hurricane.svg'
import Identification from '@department-of-veterans-affairs/mobile-assets/icons/vads/identification.svg'
import Image from '@department-of-veterans-affairs/mobile-assets/icons/vads/image.svg'
import Inbox from '@department-of-veterans-affairs/mobile-assets/icons/Inbox.svg'
import IndeterminateCheckBox from '@department-of-veterans-affairs/mobile-assets/icons/indeterminate_check_box.svg'
// import Info from '@department-of-veterans-affairs/mobile-assets/icons/Info.svg'
import Info from '@department-of-veterans-affairs/mobile-assets/icons/vads/info.svg'
import InfoOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/info_outline.svg'
import Insights from '@department-of-veterans-affairs/mobile-assets/icons/vads/insights.svg'
import Instagram from '@department-of-veterans-affairs/mobile-assets/icons/vads/instagram.svg'
import Keyboard from '@department-of-veterans-affairs/mobile-assets/icons/vads/keyboard.svg'
import Label from '@department-of-veterans-affairs/mobile-assets/icons/vads/label.svg'
import Language from '@department-of-veterans-affairs/mobile-assets/icons/vads/language.svg'
import LastPage from '@department-of-veterans-affairs/mobile-assets/icons/vads/last_page.svg'
import Launch from '@department-of-veterans-affairs/mobile-assets/icons/vads/launch.svg'
import Lightbulb from '@department-of-veterans-affairs/mobile-assets/icons/vads/lightbulb.svg'
import LightbulbOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/lightbulb_outline.svg'
import Link from '@department-of-veterans-affairs/mobile-assets/icons/vads/link.svg'
import LinkOff from '@department-of-veterans-affairs/mobile-assets/icons/vads/link_off.svg'
import Linkedin from '@department-of-veterans-affairs/mobile-assets/icons/vads/linkedin.svg'
import List from '@department-of-veterans-affairs/mobile-assets/icons/vads/list.svg'
import LocalCafe from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_cafe.svg'
import LocalFireDepartment from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_fire_department.svg'
import LocalGasStation from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_gas_station.svg'
import LocalGroceryStore from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_grocery_store.svg'
import LocalHospital from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_hospital.svg'
import LocalLaundryService from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_laundry_service.svg'
import LocalLibrary from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_library.svg'
import LocalOffer from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_offer.svg'
import LocalParking from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_parking.svg'
import LocalPharmacy from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_pharmacy.svg'
import LocalPolice from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_police.svg'
import LocalTaxi from '@department-of-veterans-affairs/mobile-assets/icons/vads/local_taxi.svg'
import LocationCity from '@department-of-veterans-affairs/mobile-assets/icons/vads/location_city.svg'
import LocationOn from '@department-of-veterans-affairs/mobile-assets/icons/vads/location_on.svg'
// import Lock from '@department-of-veterans-affairs/mobile-assets/icons/Lock.svg'
import Lock from '@department-of-veterans-affairs/mobile-assets/icons/vads/lock.svg'
import LockOpen from '@department-of-veterans-affairs/mobile-assets/icons/vads/lock_open.svg'
import LockOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/lock_outline.svg'
import Login from '@department-of-veterans-affairs/mobile-assets/icons/vads/login.svg'
import Logout from '@department-of-veterans-affairs/mobile-assets/icons/vads/logout.svg'
import Loop from '@department-of-veterans-affairs/mobile-assets/icons/vads/loop.svg'
import Mail from '@department-of-veterans-affairs/mobile-assets/icons/vads/mail.svg'
import MailOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/mail_outline.svg'
import Map from '@department-of-veterans-affairs/mobile-assets/icons/vads/map.svg'
import Masks from '@department-of-veterans-affairs/mobile-assets/icons/vads/masks.svg'
// import MedicalServices from '@department-of-veterans-affairs/mobile-assets/icons/MedicalServices.svg'
import MedicalServices from '@department-of-veterans-affairs/mobile-assets/icons/vads/medical_services.svg'
import MedicalServicesOutline from '@department-of-veterans-affairs/mobile-assets/icons/MedicalServicesOutline.svg'
import MedicalServicesOutlined from '@department-of-veterans-affairs/mobile-assets/icons/medical_services_outlined.svg'
import Medication from '@department-of-veterans-affairs/mobile-assets/icons/vads/medication.svg'
import Menu from '@department-of-veterans-affairs/mobile-assets/icons/vads/menu.svg'
import MilitaryTech from '@department-of-veterans-affairs/mobile-assets/icons/vads/military_tech.svg'
import Minus from '@department-of-veterans-affairs/mobile-assets/icons/Minus.svg'
import MoreHoriz from '@department-of-veterans-affairs/mobile-assets/icons/vads/more_horiz.svg'
import MoreVert from '@department-of-veterans-affairs/mobile-assets/icons/vads/more_vert.svg'
import MyLocation from '@department-of-veterans-affairs/mobile-assets/icons/vads/my_location.svg'
import NavigateBefore from '@department-of-veterans-affairs/mobile-assets/icons/vads/navigate_before.svg'
import NavigateFarBefore from '@department-of-veterans-affairs/mobile-assets/icons/vads/navigate_far_before.svg'
import NavigateFarNext from '@department-of-veterans-affairs/mobile-assets/icons/vads/navigate_far_next.svg'
import NavigateNext from '@department-of-veterans-affairs/mobile-assets/icons/vads/navigate_next.svg'
import NearMe from '@department-of-veterans-affairs/mobile-assets/icons/vads/near_me.svg'
import NoteAdd from '@department-of-veterans-affairs/mobile-assets/icons/vads/note_add.svg'
import Notifications from '@department-of-veterans-affairs/mobile-assets/icons/vads/notifications.svg'
import NotificationsActive from '@department-of-veterans-affairs/mobile-assets/icons/vads/notifications_active.svg'
import NotificationsNone from '@department-of-veterans-affairs/mobile-assets/icons/vads/notifications_none.svg'
import NotificationsOff from '@department-of-veterans-affairs/mobile-assets/icons/vads/notifications_off.svg'
import PaperClip from '@department-of-veterans-affairs/mobile-assets/icons/PaperClip.svg'
import Park from '@department-of-veterans-affairs/mobile-assets/icons/vads/park.svg'
import People from '@department-of-veterans-affairs/mobile-assets/icons/vads/people.svg'
import Person from '@department-of-veterans-affairs/mobile-assets/icons/vads/person.svg'
import Pets from '@department-of-veterans-affairs/mobile-assets/icons/vads/pets.svg'
// import Phone from '@department-of-veterans-affairs/mobile-assets/icons/Phone.svg'
import Phone from '@department-of-veterans-affairs/mobile-assets/icons/vads/phone.svg'
import PhoneIphone from '@department-of-veterans-affairs/mobile-assets/icons/vads/phone_iphone.svg'
import PhotoCamera from '@department-of-veterans-affairs/mobile-assets/icons/vads/photo_camera.svg'
import PlayCircle from '@department-of-veterans-affairs/mobile-assets/icons/vads/play_circle.svg'
import Print from '@department-of-veterans-affairs/mobile-assets/icons/vads/print.svg'
import PriorityHigh from '@department-of-veterans-affairs/mobile-assets/icons/vads/priority_high.svg'
import Public from '@department-of-veterans-affairs/mobile-assets/icons/vads/public.svg'
import PushPin from '@department-of-veterans-affairs/mobile-assets/icons/vads/push_pin.svg'
import QuestionMark from '@department-of-veterans-affairs/mobile-assets/icons/QuestionMark.svg'
import RadioButtonChecked from '@department-of-veterans-affairs/mobile-assets/icons/radio_button_checked.svg'
// import RadioButtonUnchecked from '@department-of-veterans-affairs/mobile-assets/icons/radio_button_unchecked.svg'
import RadioButtonUnchecked from '@department-of-veterans-affairs/mobile-assets/icons/vads/radio_button_unchecked.svg'
import RadioEmpty from '@department-of-veterans-affairs/mobile-assets/icons/RadioEmpty.svg'
import RadioFilled from '@department-of-veterans-affairs/mobile-assets/icons/RadioFilled.svg'
import Rain from '@department-of-veterans-affairs/mobile-assets/icons/vads/rain.svg'
import Redo from '@department-of-veterans-affairs/mobile-assets/icons/Redo.svg'
import ReduceCapacity from '@department-of-veterans-affairs/mobile-assets/icons/vads/reduce_capacity.svg'
// import Remove from '@department-of-veterans-affairs/mobile-assets/icons/Remove.svg'
import Remove from '@department-of-veterans-affairs/mobile-assets/icons/vads/remove.svg'
import RemoveCircle from '@department-of-veterans-affairs/mobile-assets/icons/vads/remove_circle.svg'
import Reply from '@department-of-veterans-affairs/mobile-assets/icons/Reply.svg'
import Report from '@department-of-veterans-affairs/mobile-assets/icons/vads/report.svg'
import RequestQuote from '@department-of-veterans-affairs/mobile-assets/icons/vads/request_quote.svg'
import RequestQuoteOutlined from '@department-of-veterans-affairs/mobile-assets/icons/request_quote_outlined.svg'
import Restaurant from '@department-of-veterans-affairs/mobile-assets/icons/vads/restaurant.svg'
import RssFeed from '@department-of-veterans-affairs/mobile-assets/icons/vads/rss_feed.svg'
import SafetyDivider from '@department-of-veterans-affairs/mobile-assets/icons/vads/safety_divider.svg'
import Sanitizer from '@department-of-veterans-affairs/mobile-assets/icons/vads/sanitizer.svg'
import SaveAlt from '@department-of-veterans-affairs/mobile-assets/icons/vads/save_alt.svg'
import Schedule from '@department-of-veterans-affairs/mobile-assets/icons/vads/schedule.svg'
import School from '@department-of-veterans-affairs/mobile-assets/icons/vads/school.svg'
import Science from '@department-of-veterans-affairs/mobile-assets/icons/vads/science.svg'
import Search from '@department-of-veterans-affairs/mobile-assets/icons/vads/search.svg'
import Security from '@department-of-veterans-affairs/mobile-assets/icons/vads/security.svg'
import Send from '@department-of-veterans-affairs/mobile-assets/icons/vads/send.svg'
import SentimentDissatisfied from '@department-of-veterans-affairs/mobile-assets/icons/vads/sentiment_dissatisfied.svg'
import SentimentNeutral from '@department-of-veterans-affairs/mobile-assets/icons/vads/sentiment_neutral.svg'
import SentimentSatisfied from '@department-of-veterans-affairs/mobile-assets/icons/vads/sentiment_satisfied.svg'
import SentimentSatisfiedAlt from '@department-of-veterans-affairs/mobile-assets/icons/vads/sentiment_satisfied_alt.svg'
import SentimentVeryDissatisfied from '@department-of-veterans-affairs/mobile-assets/icons/vads/sentiment_very_dissatisfied.svg'
import Settings from '@department-of-veterans-affairs/mobile-assets/icons/vads/settings.svg'
import SevereWeather from '@department-of-veterans-affairs/mobile-assets/icons/vads/severe_weather.svg'
import Share from '@department-of-veterans-affairs/mobile-assets/icons/vads/share.svg'
import Shield from '@department-of-veterans-affairs/mobile-assets/icons/vads/shield.svg'
import ShoppingBasket from '@department-of-veterans-affairs/mobile-assets/icons/vads/shopping_basket.svg'
import Snow from '@department-of-veterans-affairs/mobile-assets/icons/vads/snow.svg'
import Soap from '@department-of-veterans-affairs/mobile-assets/icons/vads/soap.svg'
import SocialDistance from '@department-of-veterans-affairs/mobile-assets/icons/vads/social_distance.svg'
import Sort from '@department-of-veterans-affairs/mobile-assets/icons/Sort.svg'
import SortArrow from '@department-of-veterans-affairs/mobile-assets/icons/vads/sort_arrow.svg'
import Spellcheck from '@department-of-veterans-affairs/mobile-assets/icons/vads/spellcheck.svg'
import Star from '@department-of-veterans-affairs/mobile-assets/icons/vads/star.svg'
import StarHalf from '@department-of-veterans-affairs/mobile-assets/icons/vads/star_half.svg'
import StarOutline from '@department-of-veterans-affairs/mobile-assets/icons/vads/star_outline.svg'
import Store from '@department-of-veterans-affairs/mobile-assets/icons/vads/store.svg'
import Support from '@department-of-veterans-affairs/mobile-assets/icons/vads/support.svg'
import SupportAgent from '@department-of-veterans-affairs/mobile-assets/icons/vads/support_agent.svg'
// import TTY from '@department-of-veterans-affairs/mobile-assets/icons/TTY.svg'
import TTY from '@department-of-veterans-affairs/mobile-assets/icons/vads/tty.svg'
import Text from '@department-of-veterans-affairs/mobile-assets/icons/Text.svg'
import TextFields from '@department-of-veterans-affairs/mobile-assets/icons/vads/text_fields.svg'
import ThumbDownAlt from '@department-of-veterans-affairs/mobile-assets/icons/vads/thumb_down_alt.svg'
import ThumbUpAlt from '@department-of-veterans-affairs/mobile-assets/icons/vads/thumb_up_alt.svg'
import Timer from '@department-of-veterans-affairs/mobile-assets/icons/vads/timer.svg'
import ToggleOff from '@department-of-veterans-affairs/mobile-assets/icons/vads/toggle_off.svg'
import ToggleOn from '@department-of-veterans-affairs/mobile-assets/icons/vads/toggle_on.svg'
import Topic from '@department-of-veterans-affairs/mobile-assets/icons/vads/topic.svg'
import Tornado from '@department-of-veterans-affairs/mobile-assets/icons/vads/tornado.svg'
import Translate from '@department-of-veterans-affairs/mobile-assets/icons/vads/translate.svg'
import Trash from '@department-of-veterans-affairs/mobile-assets/icons/Trash.svg'
import TrendingDown from '@department-of-veterans-affairs/mobile-assets/icons/vads/trending_down.svg'
import TrendingUp from '@department-of-veterans-affairs/mobile-assets/icons/vads/trending_up.svg'
import Truck from '@department-of-veterans-affairs/mobile-assets/icons/Truck.svg'
import Twitter from '@department-of-veterans-affairs/mobile-assets/icons/vads/twitter.svg'
import Undo from '@department-of-veterans-affairs/mobile-assets/icons/vads/undo.svg'
import UnfoldLess from '@department-of-veterans-affairs/mobile-assets/icons/vads/unfold_less.svg'
import UnfoldMore from '@department-of-veterans-affairs/mobile-assets/icons/vads/unfold_more.svg'
import Unread from '@department-of-veterans-affairs/mobile-assets/icons/Unread.svg'
import Update from '@department-of-veterans-affairs/mobile-assets/icons/vads/update.svg'
import UploadFile from '@department-of-veterans-affairs/mobile-assets/icons/vads/upload_file.svg'
import Verified from '@department-of-veterans-affairs/mobile-assets/icons/vads/verified.svg'
import VerifiedUser from '@department-of-veterans-affairs/mobile-assets/icons/vads/verified_user.svg'
import VideoCamera from '@department-of-veterans-affairs/mobile-assets/icons/VideoCamera.svg'
import Videocam from '@department-of-veterans-affairs/mobile-assets/icons/vads/videocam.svg'
import Visibility from '@department-of-veterans-affairs/mobile-assets/icons/vads/visibility.svg'
import VisibilityOff from '@department-of-veterans-affairs/mobile-assets/icons/vads/visibility_off.svg'
import VolumeOff from '@department-of-veterans-affairs/mobile-assets/icons/vads/volume_off.svg'
import Warning from '@department-of-veterans-affairs/mobile-assets/icons/vads/warning.svg'
import Wash from '@department-of-veterans-affairs/mobile-assets/icons/vads/wash.svg'
import Wifi from '@department-of-veterans-affairs/mobile-assets/icons/vads/wifi.svg'
import Work from '@department-of-veterans-affairs/mobile-assets/icons/vads/work.svg'
import X from '@department-of-veterans-affairs/mobile-assets/icons/vads/x.svg'
import Youtube from '@department-of-veterans-affairs/mobile-assets/icons/vads/youtube.svg'
import ZoomIn from '@department-of-veterans-affairs/mobile-assets/icons/vads/zoom_in.svg'
import ZoomOut from '@department-of-veterans-affairs/mobile-assets/icons/vads/zoom_out.svg'
import ZoomOutMap from '@department-of-veterans-affairs/mobile-assets/icons/vads/zoom_out_map.svg'

export const IconMap = {
  AccessibilityNew,
  AccessibleForward,
  AccountBalance,
  AccountBox,
  AccountCircle,
  Add,
  AddCircle,
  AddCircleOutline,
  Adjust,
  Alarm,
  AlternateEmail,
  Announcement,
  Api,
  AppStore,
  ArrowBack,
  ArrowDownward,
  ArrowDropDown,
  ArrowDropUp,
  ArrowForward,
  ArrowUpward,
  Assessment,
  Assignment,
  AssignmentTurnedIn,
  AttachFile,
  AttachMoney,
  Autorenew,
  Backpack,
  Bathtub,
  Bedding,
  Bookmark,
  BugReport,
  Build,
  Building,
  Bullet,
  Calendar,
  CalendarToday,
  Campaign,
  Camping,
  Cancel,
  Chat,
  Check,
  CheckBox,
  CheckBoxEmpty,
  CheckBoxError,
  CheckBoxFilled,
  CheckBoxIntermediate,
  CheckBoxOutlineBlank,
  CheckCircle,
  CheckCircleOutline,
  Checkroom,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheckMark,
  CleanHands,
  Close,
  ClosedCaption,
  Clothes,
  Cloud,
  Code,
  Comment,
  Compose,
  ConnectWithoutContact,
  Construction,
  ConstructionWorker,
  ContactPage,
  ContentCopy,
  Coronavirus,
  CreditCard,
  Deck,
  Delete,
  Description,
  DescriptionOutline,
  DescriptionOutlined,
  DeviceThermostat,
  Directions,
  DirectionsBike,
  DirectionsBus,
  DirectionsCar,
  DirectionsWalk,
  DoNotDisturb,
  DoNotTouch,
  DragHandle,
  Eco,
  Edit,
  ElectricalServices,
  Ellipsis,
  EmojiEvents,
  Error,
  ErrorOutline,
  Event,
  EventAvailable,
  ExclamationCircle,
  ExclamationTriangle,
  ExpandLess,
  ExpandMore,
  ExternalLink,
  Facebook,
  FastForward,
  FastRewind,
  Favorite,
  FavoriteBorder,
  Fax,
  FileDownload,
  FileInvoiceDollar,
  FileInvoiceDollarOutline,
  FilePresent,
  FileUpload,
  FilterAlt,
  FilterList,
  Fingerprint,
  FirstPage,
  Flag,
  Flickr,
  Flight,
  Flooding,
  Folder,
  FolderOpen,
  FormatQuote,
  FormatSize,
  Forum,
  Github,
  GooglePlay,
  GridView,
  GroupAdd,
  Groups,
  Handshake,
  Hearing,
  HearingDisabled,
  Help,
  HelpOutline,
  HighlightOff,
  History,
  Home,
  HomeOutline,
  HomeOutlined,
  Hospital,
  Hotel,
  HourglassEmpty,
  HowToReg,
  Hurricane,
  Identification,
  Image,
  Inbox,
  IndeterminateCheckBox,
  Info,
  InfoOutline,
  Insights,
  Instagram,
  Keyboard,
  Label,
  Language,
  LastPage,
  Launch,
  Lightbulb,
  LightbulbOutline,
  Link,
  LinkOff,
  Linkedin,
  List,
  LocalCafe,
  LocalFireDepartment,
  LocalGasStation,
  LocalGroceryStore,
  LocalHospital,
  LocalLaundryService,
  LocalLibrary,
  LocalOffer,
  LocalParking,
  LocalPharmacy,
  LocalPolice,
  LocalTaxi,
  LocationCity,
  LocationOn,
  Lock,
  LockOpen,
  LockOutline,
  Login,
  Logout,
  Loop,
  Mail,
  MailOutline,
  Map,
  Masks,
  MedicalServices,
  MedicalServicesOutline,
  MedicalServicesOutlined,
  Medication,
  Menu,
  MilitaryTech,
  Minus,
  MoreHoriz,
  MoreVert,
  MyLocation,
  NavigateBefore,
  NavigateFarBefore,
  NavigateFarNext,
  NavigateNext,
  NearMe,
  NoteAdd,
  Notifications,
  NotificationsActive,
  NotificationsNone,
  NotificationsOff,
  PaperClip,
  Park,
  People,
  Person,
  Pets,
  Phone,
  PhoneIphone,
  PhotoCamera,
  PlayCircle,
  Print,
  PriorityHigh,
  Public,
  PushPin,
  QuestionMark,
  RadioButtonChecked,
  RadioButtonUnchecked,
  RadioEmpty,
  RadioFilled,
  Rain,
  Redo,
  ReduceCapacity,
  Remove,
  RemoveCircle,
  Reply,
  Report,
  RequestQuote,
  RequestQuoteOutlined,
  Restaurant,
  RssFeed,
  SafetyDivider,
  Sanitizer,
  SaveAlt,
  Schedule,
  School,
  Science,
  Search,
  Security,
  Send,
  SentimentDissatisfied,
  SentimentNeutral,
  SentimentSatisfied,
  SentimentSatisfiedAlt,
  SentimentVeryDissatisfied,
  Settings,
  SevereWeather,
  Share,
  Shield,
  ShoppingBasket,
  Snow,
  Soap,
  SocialDistance,
  Sort,
  SortArrow,
  Spellcheck,
  Star,
  StarHalf,
  StarOutline,
  Store,
  Support,
  SupportAgent,
  TTY,
  Text,
  TextFields,
  ThumbDownAlt,
  ThumbUpAlt,
  Timer,
  ToggleOff,
  ToggleOn,
  Topic,
  Tornado,
  Translate,
  Trash,
  TrendingDown,
  TrendingUp,
  Truck,
  Twitter,
  Undo,
  UnfoldLess,
  UnfoldMore,
  Unread,
  Update,
  UploadFile,
  Verified,
  VerifiedUser,
  VideoCamera,
  Videocam,
  Visibility,
  VisibilityOff,
  VolumeOff,
  Warning,
  Wash,
  Wifi,
  Work,
  X,
  Youtube,
  ZoomIn,
  ZoomOut,
  ZoomOutMap,
}
