#
# Checking instances where we're integrating with apps
#

name: 'Check Component Integrations'

on:
  workflow_dispatch:
  push:
    paths: ['packages/components/**']
    branches:
      - main

jobs:
  check-integrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (va-mobile-library)
        id: clone-lib
        uses: actions/checkout@v4
        with:
          path: va-mobile-library

      - name: Checkout (va-mobile-app)
        id: clone-app
        uses: actions/checkout@v4
        with:
          repository: department-of-veterans-affairs/va-mobile-app
          ref: 'develop'
          path: va-mobile-app

      - name: Install dependencies (va-mobile-library)
        working-directory: va-mobile-library
        run: yarn install --immutable

      - name: Install dependencies (va-mobile-app)
        working-directory: va-mobile-app/VAMobile
        run: yarn install

      - name: Install local component library
        working-directory: va-mobile-app/VAMobile
        run: yarn add file:../../va-mobile-library/packages/components

      - name: Compile TypeScript (va-mobile-app)
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd va-mobile-app/VAMobile
            yarn tsc:compile

      - name: Run Unit Tests (va-mobile-app)
        id: unit-tests
        working-directory: va-mobile-app/VAMobile
        run: yarn test --testTimeout=30000
        continue-on-error: true

      # - name: Retry failed unit tests
      #   if: steps.unit-tests.outcome == 'failure'
      #   working-directory: va-mobile-app/VAMobile
      #   run: yarn test --testTimeout=30000
      #   continue-on-error: true
