#
# Code checks – linting and unit tests
#

name: 'Code Checks'

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run eslint
        run: yarn lint
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'packages/components/yarn.lock'
      - name: Install dependencies
        working-directory: packages/components
        run: yarn install --immutable
      - name: yarn test
        working-directory: packages/components
        run: yarn test
