name: Publish Documentation
on:
  workflow_dispatch:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
           node-version: '18'
           cache: 'yarn'

        - name: Install npm dependencies
          working-directory: ./packages/components
          run: yarn install --immutable

        - name: Build and Depoy documentation
          working-directory: ./packages/components
          run: yarn storybook:deploy

        # - name: Deploy
        #   uses: peaceiris/actions-gh-pages@v3
        #   with:
        #     deploy_key: ${{ secrets.GITHUB_TOKEN }}
        #     publish_dir: ./packages/components/storybook-static
