name: Publish Documentation
on:
  workflow_dispatch:
  push:
    # branches:
    #   - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install npm dependencies
        working-directory: ./packages/components
        run: yarn install --immutable

      - name: Build documentation
        working-directory: ./packages/components
        run: yarn storybook:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/components/storybook-static
