# Bump version and release a specific package to NPM
# https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml

name: 'Publish Package'

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true
        type: choice
        options:
          - components
          - tokens
      version_bump:
        description: Version bump
        required: true
        type: choice
        options:
          - alpha
          - beta
          - patch
          - minor
          - major

jobs:
  publish-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/${{ inputs.package }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version-file: '.nvmrc'
      - name: Bump version and publish to NPM
        id: bump-version
        run: |
          NPM_PACKAGE=$(jq -r .name package.json)
          echo "NPM_PACKAGE_NAME=$NPM_PACKAGE" >> "$GITHUB_OUTPUT"

          echo "NPM Package name: $NPM_PACKAGE"
          CURRENT_VERSION=$(jq -r .version package.json)

          LATEST_VERSION=$(npm view @department-of-veterans-affairs/mobile-component-library versions --json | jq -r '.[-1]')
          echo "Latest NPM version: $LATEST_VERSION"

          if [[ "$CURRENT_VERSION" != "$LATEST_VERSION" ]]; then
            echo "Setting package.json version to $LATEST_VERSION"
            npm version $LATEST_VERSION
          fi


          BUMP=${{ inputs.version_bump }}
          echo "Bumping version: $BUMP"
          if [[ "$BUMP" == "alpha" ]] || [[ "$BUMP" == "beta" ]]; then
            npm version prerelease --preid $BUMP
            npm publish --access public --tolerate-republish --tag $BUMP
          else
            npm version $BUMP
            npm publish --access public --tolerate-republish
          fi

          NEW_VERSION=$(jq -r .version package.json)
          echo "Updated version: $NEW_VERSION"

          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "GIT_TAG=${{ inputs.package }}-v$NEW_VERSION" >> "$GITHUB_OUTPUT"
      - name: Commit package.json changes and tag
        run: |
          git config --global user.name 'VA Automation Bot'
          git config --global user.email 'va-mobileapp@adhocteam.us'
          git add package.json
          git commit -m '[TEST] Version bump: ${{ steps.bump-version.outputs.GIT_TAG }}'
          git push
          TAG=${{ steps.bump-version.outputs.GIT_TAG }}
          echo $TAG
          git tag -a $TAG -m $TAG
          git push origin $TAG
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: C022SV53ASZ # C05DQPHUVNZ
          # For posting a simple plain text message
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.bump-version.outputs.NEW_VERSION }} of ${{ steps.bump-version.outputs.NPM_PACKAGE_NAME }} has been published to NPM \n • <https://www.npmjs.com/package/${{ steps.bump-version.outputs.NPM_PACKAGE_NAME }}|NPM Link>  \n • <https://github.com/department-of-veterans-affairs/va-mobile-library/releases/tag/${{ steps.bump-version.outputs.GIT_TAG }}|Git Tag>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
