name: Publish Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - run: yarn

        - run: yarn storybook:build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3

          with:
            deploy_key: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./packages/components/storybook-static