# Builds the tokens package to update the figma folder

name: 'Build Tokens Package'

on:
  workflow_dispatch:
  push:
    paths: ['packages/tokens/**']
    branches:
      - main

jobs:
  tokens-build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ jobs.tokens-build.steps.diff }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VA_MOBILE_ROBOT_GITHUB_PAT }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn install
      - name: Build tokens
        run: |
          yarn tokens:build
      - name: Prepare commit
        working-directory: packages/tokens
        run: |
          git config --global user.name 'VA Automation Bot'
          git config --global user.email 'va-mobileapp@adhocteam.us'
          git pull
          git add -f figma/
      - name: Check figma diff
        id: diff
        working-directory: packages/tokens
        run: | 
          git commit --dry-run
      - name: No changes to figma tokens
        if: failure() && steps.diff.conclusion == 'failure'
        run: |
          echo No changes to figma tokens
      - name: Commit latest figma tokens
        if: success() && steps.diff.conclusion == 'success'
        working-directory: packages/tokens
        run: |
          git commit -m 'Build latest figma tokens'
          git push
