name: Check for token changes

on:
  pull_request:
    types: [opened, edited]
  push:

defaults:
  run:
    working-directory: packages/tokens

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VA_MOBILE_ROBOT_GITHUB_PAT }}
      - name: Compare tokens
        if: ${{ contains(github.ref, 'packages/tokens/department-of-veterans-affairs/css-library') }}
        run: |
          yarn && yarn tokens:build
          cd dist/js
          cp colors.js colors_new.js
          git checkout main
          yarn && yarn tokens:build

          if diff -q colors.js colors_new.js > /dev/null; then
            echo "Files have the same contents."
          else
            echo "Files have different contents."
          fi
