name: Compare tokens

on:
  pull_request:
    types: [opened, edited]
  push:

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VA_MOBILE_ROBOT_GITHUB_PAT }}
      - name: Compare tokens
        if: ${{ contains(github.event.pull_request.title, '@department-of-veterans-affairs/css-library') }}
        run: |
          echo 'true'
